# Generated by Django 5.1.1 on 2024-10-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviour',
            name='agent_greeting',
            field=models.CharField(default="Hello! I'm Intervuo, AI interviewer. Please describe your experience and skills related to the position you're applying for", max_length=250),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='agent_prompt',
            field=models.TextField(default="\n        As an AI interviewer, your role is to conduct an interview by assessing the candidate's skills and experience.\n        Begin by acknowledging the candidate's readiness. Prompt the candidate to explain their skills and areas of expertise.\n        If the candidate meets the basic requirements for the position, proceed to ask between 3 and 10 relevant questions.\n        Evaluate each response based on predefined criteria and accumulate a score.\n        If the candidate does not meet initial requirements, gently inform them.\n        After all questions are answered, calculate their final score to determine their qualification for the role.\n        Provide feedback based on the score, stating whether they are suitable for the position.\n        Finally, ensure to clear any session data or memory pertaining to this interview process."),
        ),
        migrations.AlterField(
            model_name='identity',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('arabic', 'Arabic'), ('bulgarian', 'Bulgarian'), ('chinese', 'Chinese'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('filipino', 'Filipino'), ('finnish', 'Finnish'), ('french', 'French'), ('german', 'German'), ('greek', 'Greek'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('malay', 'Malay'), ('norwegian', 'Norwegian'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('slovak', 'Slovak'), ('spanish', 'Spanish'), ('swedish', 'Swedish'), ('turkish', 'Turkish'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese')], default='english', max_length=10),
        ),
        migrations.AlterField(
            model_name='identity',
            name='voice',
            field=models.CharField(choices=[('adam', 'Adam'), ('alice', 'Alice'), ('bill', 'Bill'), ('brian', 'Brian'), ('callum', 'Callum'), ('charlie', 'Charlie'), ('charlotte', 'Charlotte'), ('chris', 'Chris'), ('daniel', 'Daniel'), ('george', 'George'), ('liam', 'Liam'), ('lily', 'Lily'), ('matilda', 'Matilda'), ('sarah', 'Sarah')], default='adam', max_length=9),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='agent_llm',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT 4o mini'), ('gpt-4o', 'GPT 4o')], default='gpt-4o-mini', max_length=11),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='custom_knowledge',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='knowledgefileitem',
            name='status_url',
            field=models.CharField(blank=True, choices=[('Indexed', 'Index'), ('Active', 'Active'), ('Errored', 'Error')], default='Indexed', max_length=7, null=True),
        ),
    ]
