# Generated by Django 5.1.1 on 2024-10-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledge',
            old_name='custom_knowlegde',
            new_name='custom_knowledge',
        ),
        migrations.RenameField(
            model_name='knowledgefileitem',
            old_name='knowlegde_files',
            new_name='knowledge_files',
        ),
    ]
