# Generated by Django 5.1.1 on 2024-10-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_rename_custom_knowlegde_knowledge_custom_knowledge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgefiles',
            name='knowledge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='console.knowledge'),
        ),
    ]
