# Generated by Django 5.1.1 on 2024-10-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_applicant_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='excitement',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='impressive_work',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='level',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='other_information',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='past_experience',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='get_just_happend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='init',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='last_info_msg_ai',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='last_info_msg_human',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='agent_greeting',
            field=models.CharField(default="Hello! I am your AI interviewer. Please describe your experience and skills related to the position you're applying for", max_length=250),
        ),
    ]
