# Generated by Django 5.1.1 on 2024-10-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_applicant_excitement_applicant_impressive_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='agent_greeting',
            field=models.CharField(default='Hello! I am your AI interviewer. Shall we start with basic setup before starting the real journey?', max_length=250),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='agent_prompt',
            field=models.TextField(default="\n        As an AI interviewer, your role is to conduct an interview by combining candidate's skills and experience and other user's data.\n        If the candidate meets the basic requirements for the position, proceed to ask between 3 and 10 relevant questions.\n        Evaluate each response based on predefined criteria and accumulate a score.\n        If the candidate does not meet initial requirements, gently inform them.\n        After all questions are answered, calculate their final score to determine their qualification for the role.\n        Provide feedback based on the score, stating whether they are suitable for the position.\n        Finally, ensure to clear any session data or memory pertaining to this interview process."),
        ),
    ]
