# Generated by Django 5.1.1 on 2024-10-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_alter_applicant_name_alter_behaviour_agent_greeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
