# Generated by Django 5.1.1 on 2024-10-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_alter_applicant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
